OPENAI_API_KEY = "tu_api_key_openai"

CREDENCIALES_GOOGLE = """
{
  "type": "service_account",
  "project_id": "tu_project_id",
  "private_key_id": "xxxx",
  "private_key": "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n",
  "client_email": "acceso-sheets@registro-horas-maquinaria.iam.gserviceaccount.com",
  "client_id": "xxxx",
  ...
}
"""
