# .streamlit/secrets.toml en GitHub (version gen√©rica)
OPENAI_API_KEY = "TU_API_KEY_OPENAI"

[gcp_service_account]
project_id = "TU_PROJECT_ID"
client_email = "TU_CLIENT_EMAIL"
client_id = "TU_CLIENT_ID"
private_key = """
-----BEGIN PRIVATE KEY-----
TU_CLAVE_PRIVADA_AQUI
-----END PRIVATE KEY-----
"""
